import type { Metadata } from 'next'
import './globals.css'
import AuthContext from "@/app/AuthContext"
import { Inter } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next ChatApp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
          className={inter.className}>
          <AuthContext>
              {children}
          </AuthContext>
      </body>
    </html>
  )
}
